### Get All Scores from Scoreboard
GET http://localhost:3001/api/scoreboard/all
Content-Type: application/json

### Get All Scores from Scoreboard sorted by oldScore
GET http://localhost:3001/api/scoreboard/all?sortBy=oldScore
Content-Type: application/json

### Get my Rank
GET http://localhost:3001/api/scoreboard/myRank/1
Content-Type: application/json

### Get my Rank with error
GET http://localhost:3001/api/scoreboard/myRank/-1
Content-Type: application/json